services:
  gitbackup:
    image: jongsx/gitbackup:latest
    container_name: gitbackup
    environment:
      - GITHUB_USER=trganda
      - GITBACKUP_DIR=/opt/gitbackup
      - CRON=*/1 * * * *
    volumes:
      - ./gitbackup:/opt/gitbackup