version: "3"

services:
  nifi:
    image: "apache/nifi:1.20.0"
    restart: always
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
      NIFI_JVM_DEBUGGER: 1
