version: "3"

services:
  webdav:
    image: jongsx/webdav:2.1.0
    environment:
      - USERNAME=trganda
      - PASSWORD=changeme
    volumes:
      - D:\Documents\webdav:/var/lib/webdav
      # - ./conf/cert.crt:/usr/local/apache2/conf/server.crt
      # - ./conf/privkey.key:/usr/local/apache2/conf/server.key
    ports:
      - 443:443

volumes:
  webdav-data:
