services:
  nginx:
    image: nginx:stable
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.crt:/etc/nginx/cert.crt
      - ./cert.key:/etc/nginx/cert.key
    ports:
      - "8443:443"
    depends_on:
      - ztncui

  ztncui:
    container_name: ztncui
    image: keynetworks/ztncui:latest
    restart: on-failure:3
    environment:
      - MYADDR=1.1.1.1 #改成自己的服务器公网IP
      - HTTP_PORT=4000
      - HTTP_ALL_INTERFACES=yes
      - ZTNCUI_PASSWD=ztncuipasswd
      - TZ=Asia/Shanghai
    # ports:
      # - '4000:4000' # web控制台入口
      # - '9993:9993'
      # - '9993:9993/udp'
      # - '3180:3180' # planet/moon 文件在线下载入口，如不对外提供。可防火墙禁用此端口。
    # volumes:
    #     - './zerotier-one:/var/lib/zerotier-one'
    #     - './ztncui/etc:/opt/key-networks/ztncui/etc'