version: '3.6'

services:
  web:
    image: 'gitlab/gitlab-ce:16.0.0-ce.0'
    restart: always
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
      - ./config:/etc/gitlab
    shm_size: '256m'
