version: '3.6'

services:
  web:
    image: 'gitlab/gitlab-ce:16.0.0-ce.0'
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
      - ./config:/etc/gitlab
    shm_size: '256m'
