version: '3.4'
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key:/root/ssl/key.pem
      - ./cert:/root/ssl/cert.pem
    ports:
      - "8443:443"
    depends_on:
      - archiva
    networks:
      - archiva

  archiva:
    image: xetusoss/archiva
    volumes:
      - ./data:/archiva-data
    restart: always
    networks:
      - archiva
    environment:
      # must set PROXY_BASE_URL, otherwise the request will be block by archiva since CSRF_TOKE.
      # refer: https://lists.apache.org/thread/04o7sfy4oh5gymv2l9o0w0x195xy4wdr
      PROXY_BASE_URL: https://archiva.example.com:8443
      SMTP_HOST: smtp
      SMTP_PORT: 1025
    mem_limit: 512m

  smtp:
    image: mailhog/mailhog:latest
    ports: [ "8025:8025" ]
    networks:
      - archiva

volumes:
  archiva-data-vol:

networks:
  archiva:
