version: "3.2"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tomcat
    networks:
      - webapp
  tomcat:
    image: tomcat:8.5.84
    volumes:
      - ./server.xml:/usr/local/tomcat/conf/server.xml
      - ./logs/:/usr/local/tomcat/logs/
      - ./web.xml:/usr/local/tomcat/webapps.dist/examples/WEB-INF/web.xml
      # - ./examples/:/usr/local/tomcat/webapps/examples
    restart: always
    networks:
      - webapp

networks:
  webapp:
