services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl
      - ./html:/usr/share/nginx/html
    ports:
      - 8000:443