version: '3'
services:
  joomla:
    # platform: linux/x86_64
    image: joomla:4.2.7
    links:
      - mysql:joomla
    depends_on:
      - mysql
    environment:
      - JOOMLA_DB_HOST=mysql:3306
      - JOOMLA_DB_USER=root
      - JOOMLA_DB_PASSWORD=root
      - JOOMLA_DB_NAME=joomla
    ports:
      - "8080:80"
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
